### ISSUE TITLE
How can I run your codes on Windows system

### ISSUE THREAD

**Issue by Zest86** [OptimusPrimus/dcase2020_workshop#1]

**Comment by OptimusPrimus** [comment]
Unfortunately, I do not own a Windows license. Did you encounter any specific error? 

For now, I've updated the 'environment.yml' file to exclude platform-specific the build versions, but it might still contain platform-specific packages. Pull the latest version and reinstall the environment (`conda remove --name dcase2020_workshop --all` and `conda env create -f environment.yml`). Let me know if I can do anything else for you to make this work.
